spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/study?serverTimezone=Asia/Shanghai
#  resources:
#    static-locations:
#      - classpath:/META-INF/resources/
#      - classpath:/resources/
#      - classpath:/static/
#      - classpath:/public/
  # 关闭thymleaf的缓存
  thymeleaf:
    cache: false

  messages:
    basename: i18n.login
  mvc:
    format:
      date: yyyy-MM-dd
    favicon:
      enabled: false

debug: true
server:
  error:
    include-exception: true
    include-message: always

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  reasonable: true